intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.
import impl_libs += godot-cpp%liba{godot-cpp}

libs{gdextension}: {hxx ixx txx cxx}{**} $impl_libs $intf_libs

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

{hbmis objs}{*}: cxx.poptions += -DGDEXTENSION_SHARED_BUILD

# Export options.
#
# lib{gdextension}:
# {
#   cxx.export.poptions = "-I$out_root" "-I$src_root"
#   cxx.export.libs = $intf_libs
# }

libs{gdextension}: cxx.export.poptions += -DGDEXTENSION_SHARED

libs{gdextension}: install = false
