pub_hdrs = {hxx ixx txx}{**}

./ : $pub_hdrs

# Install into the godot-cpp/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/
  install.subdirs = true
}
